language: python
python: 2.7
cache:
  directories:
  - $HOME/.pylint.d
  - eggs
  - parts/node
matrix:
  fast_finish: true
install:
  - virtualenv .
  - bin/pip install -r requirements.txt
  - bin/buildout annotate
  - bin/buildout
script:
- bin/code-analysis
- bin/test
- bin/pylint --py3k --disable=no-absolute-import src/brasil/gov/barra
after_success:
- pip install coverage
- coverage run bin/test
# Coveralls
- pip install coveralls
- coveralls
# Codacy
- coverage xml
- pip install codacy-coverage
- python-codacy-coverage -r coverage.xml
notifications:
  irc: irc.freenode.org#plonegovbr
